// Mocks generated by Mockito 5.4.6 from annotations
// in guardianes_mobile/test/features/cards/data/repositories/card_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:guardianes_mobile/features/cards/data/datasources/card_remote_datasource.dart'
    as _i4;
import 'package:guardianes_mobile/features/cards/data/models/card_model.dart'
    as _i8;
import 'package:guardianes_mobile/features/cards/data/models/card_scan_result_model.dart'
    as _i2;
import 'package:guardianes_mobile/features/cards/data/models/collected_card_model.dart'
    as _i6;
import 'package:guardianes_mobile/features/cards/data/models/collection_statistics_model.dart'
    as _i3;
import 'package:guardianes_mobile/features/cards/domain/entities/card.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCardScanResultModel_0 extends _i1.SmartFake
    implements _i2.CardScanResultModel {
  _FakeCardScanResultModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionStatisticsModel_1 extends _i1.SmartFake
    implements _i3.CollectionStatisticsModel {
  _FakeCollectionStatisticsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRemoteDataSource extends _i1.Mock
    implements _i4.CardRemoteDataSource {
  MockCardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CardScanResultModel> scanQRCode(
    int? guardianId,
    String? qrCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanQRCode,
          [
            guardianId,
            qrCode,
          ],
        ),
        returnValue: _i5.Future<_i2.CardScanResultModel>.value(
            _FakeCardScanResultModel_0(
          this,
          Invocation.method(
            #scanQRCode,
            [
              guardianId,
              qrCode,
            ],
          ),
        )),
      ) as _i5.Future<_i2.CardScanResultModel>);

  @override
  _i5.Future<List<_i6.CollectedCardModel>> getGuardianCards(
    int? guardianId, {
    _i7.CardElement? element,
    _i7.CardRarity? rarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuardianCards,
          [guardianId],
          {
            #element: element,
            #rarity: rarity,
          },
        ),
        returnValue: _i5.Future<List<_i6.CollectedCardModel>>.value(
            <_i6.CollectedCardModel>[]),
      ) as _i5.Future<List<_i6.CollectedCardModel>>);

  @override
  _i5.Future<_i3.CollectionStatisticsModel> getCollectionStatistics(
          int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionStatistics,
          [guardianId],
        ),
        returnValue: _i5.Future<_i3.CollectionStatisticsModel>.value(
            _FakeCollectionStatisticsModel_1(
          this,
          Invocation.method(
            #getCollectionStatistics,
            [guardianId],
          ),
        )),
      ) as _i5.Future<_i3.CollectionStatisticsModel>);

  @override
  _i5.Future<List<_i6.CollectedCardModel>> getRecentlyCollected(
    int? guardianId,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyCollected,
          [
            guardianId,
            limit,
          ],
        ),
        returnValue: _i5.Future<List<_i6.CollectedCardModel>>.value(
            <_i6.CollectedCardModel>[]),
      ) as _i5.Future<List<_i6.CollectedCardModel>>);

  @override
  _i5.Future<_i6.CollectedCardModel?> getRarestCard(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRarestCard,
          [guardianId],
        ),
        returnValue: _i5.Future<_i6.CollectedCardModel?>.value(),
      ) as _i5.Future<_i6.CollectedCardModel?>);

  @override
  _i5.Future<List<_i8.CardModel>> searchCards({
    String? name,
    _i7.CardElement? element,
    _i7.CardRarity? rarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCards,
          [],
          {
            #name: name,
            #element: element,
            #rarity: rarity,
          },
        ),
        returnValue: _i5.Future<List<_i8.CardModel>>.value(<_i8.CardModel>[]),
      ) as _i5.Future<List<_i8.CardModel>>);

  @override
  _i5.Future<_i8.CardModel?> getCard(int? cardId) => (super.noSuchMethod(
        Invocation.method(
          #getCard,
          [cardId],
        ),
        returnValue: _i5.Future<_i8.CardModel?>.value(),
      ) as _i5.Future<_i8.CardModel?>);
}
