apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardianes-de-gaia.secretName" . }}
  labels:
    {{- include "guardianes-de-gaia.labels" . | nindent 4 }}
type: Opaque
data:
  # Database passwords
  mysql-password: {{ .Values.mysql.auth.password | b64enc }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc }}
  
  # Redis password
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  {{- end }}
  
  # RabbitMQ passwords
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | b64enc }}
  
  # JWT Secret
  jwt-secret: {{ randAlphaNum 32 | b64enc }}
  
  # Grafana admin password
  {{- if .Values.monitoring.grafana.enabled }}
  grafana-admin-password: {{ .Values.monitoring.grafana.adminPassword | b64enc }}
  {{- end }}