apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardianes-de-gaia.secretName" . }}
  labels:
    {{- include "guardianes-de-gaia.labels" . | nindent 4 }}
type: Opaque
data:
  # Database passwords (support both internal and external)
  {{- if .Values.mysql.enabled }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc }}
  {{- else if .Values.externalDatabase }}
  # External database credentials should be managed separately in production
  external-db-host: {{ .Values.externalDatabase.host | b64enc }}
  external-db-port: {{ .Values.externalDatabase.port | toString | b64enc }}
  external-db-database: {{ .Values.externalDatabase.database | b64enc }}
  external-db-username: {{ .Values.externalDatabase.username | b64enc }}
  {{- end }}
  
  # Redis password (support both internal and external)
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  {{- end }}
  {{- else if .Values.externalRedis }}
  # External Redis credentials should be managed separately in production
  external-redis-host: {{ .Values.externalRedis.host | b64enc }}
  external-redis-port: {{ .Values.externalRedis.port | toString | b64enc }}
  {{- end }}
  
  # RabbitMQ passwords (support both internal and external)
  {{- if .Values.rabbitmq.enabled }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | b64enc }}
  {{- else if .Values.externalRabbitmq }}
  # External RabbitMQ credentials should be managed separately in production
  external-rabbitmq-host: {{ .Values.externalRabbitmq.host | b64enc }}
  external-rabbitmq-port: {{ .Values.externalRabbitmq.port | toString | b64enc }}
  external-rabbitmq-username: {{ .Values.externalRabbitmq.username | b64enc }}
  {{- end }}
  
  # JWT Secret
  jwt-secret: {{ randAlphaNum 32 | b64enc }}
  
  # Grafana admin password
  {{- if .Values.monitoring.grafana.enabled }}
  grafana-admin-password: {{ .Values.monitoring.grafana.adminPassword | b64enc }}
  {{- end }}