{{- if and .Values.serviceAccount .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guardianes-de-gaia.serviceAccountName" . }}
  labels:
    {{- include "guardianes-de-gaia.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if .Values.serviceAccount.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "guardianes-de-gaia.fullname" . }}-rbac
  labels:
    {{- include "guardianes-de-gaia.labels" . | nindent 4 }}
rules:
  # Allow reading pods for health checks
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # Allow reading services for service discovery
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  # Allow reading endpoints for load balancing
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]
  # Allow reading configmaps for configuration
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  # Allow reading secrets for credentials
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "guardianes-de-gaia.fullname" . }}-rbac
  labels:
    {{- include "guardianes-de-gaia.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "guardianes-de-gaia.fullname" . }}-rbac
subjects:
  - kind: ServiceAccount
    name: {{ include "guardianes-de-gaia.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}