// Mocks generated by Mockito 5.4.6 from annotations
// in guardianes_mobile/test/features/walking/data/repositories/step_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:guardianes_mobile/features/walking/data/datasources/step_remote_datasource.dart'
    as _i5;
import 'package:guardianes_mobile/features/walking/data/models/current_step_count_response_dto.dart'
    as _i3;
import 'package:guardianes_mobile/features/walking/data/models/step_history_response_dto.dart'
    as _i4;
import 'package:guardianes_mobile/features/walking/data/models/step_submission_request_dto.dart'
    as _i7;
import 'package:guardianes_mobile/features/walking/data/models/step_submission_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStepSubmissionResponseDto_0 extends _i1.SmartFake
    implements _i2.StepSubmissionResponseDto {
  _FakeStepSubmissionResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCurrentStepCountResponseDto_1 extends _i1.SmartFake
    implements _i3.CurrentStepCountResponseDto {
  _FakeCurrentStepCountResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStepHistoryResponseDto_2 extends _i1.SmartFake
    implements _i4.StepHistoryResponseDto {
  _FakeStepHistoryResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StepRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStepRemoteDataSource extends _i1.Mock
    implements _i5.StepRemoteDataSource {
  MockStepRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.StepSubmissionResponseDto> submitSteps(
    int? guardianId,
    _i7.StepSubmissionRequestDto? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitSteps,
          [
            guardianId,
            request,
          ],
        ),
        returnValue: _i6.Future<_i2.StepSubmissionResponseDto>.value(
            _FakeStepSubmissionResponseDto_0(
          this,
          Invocation.method(
            #submitSteps,
            [
              guardianId,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i2.StepSubmissionResponseDto>);

  @override
  _i6.Future<_i3.CurrentStepCountResponseDto> getCurrentStepCount(
          int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentStepCount,
          [guardianId],
        ),
        returnValue: _i6.Future<_i3.CurrentStepCountResponseDto>.value(
            _FakeCurrentStepCountResponseDto_1(
          this,
          Invocation.method(
            #getCurrentStepCount,
            [guardianId],
          ),
        )),
      ) as _i6.Future<_i3.CurrentStepCountResponseDto>);

  @override
  _i6.Future<_i4.StepHistoryResponseDto> getStepHistory(
    int? guardianId,
    String? fromDate,
    String? toDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStepHistory,
          [
            guardianId,
            fromDate,
            toDate,
          ],
        ),
        returnValue: _i6.Future<_i4.StepHistoryResponseDto>.value(
            _FakeStepHistoryResponseDto_2(
          this,
          Invocation.method(
            #getStepHistory,
            [
              guardianId,
              fromDate,
              toDate,
            ],
          ),
        )),
      ) as _i6.Future<_i4.StepHistoryResponseDto>);
}
