// Mocks generated by Mockito 5.4.6 from annotations
// in guardianes_mobile/test/features/cards/presentation/bloc/card_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:guardianes_mobile/features/cards/domain/entities/card.dart'
    as _i11;
import 'package:guardianes_mobile/features/cards/domain/entities/card_collection.dart'
    as _i4;
import 'package:guardianes_mobile/features/cards/domain/entities/card_scan_result.dart'
    as _i3;
import 'package:guardianes_mobile/features/cards/domain/entities/collected_card.dart'
    as _i12;
import 'package:guardianes_mobile/features/cards/domain/entities/collection_statistics.dart'
    as _i5;
import 'package:guardianes_mobile/features/cards/domain/repositories/card_repository.dart'
    as _i2;
import 'package:guardianes_mobile/features/cards/domain/usecases/get_card_collection.dart'
    as _i8;
import 'package:guardianes_mobile/features/cards/domain/usecases/get_collection_statistics.dart'
    as _i9;
import 'package:guardianes_mobile/features/cards/domain/usecases/scan_qr_code.dart'
    as _i6;
import 'package:guardianes_mobile/features/cards/domain/usecases/search_cards.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCardRepository_0 extends _i1.SmartFake
    implements _i2.CardRepository {
  _FakeCardRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCardScanResult_1 extends _i1.SmartFake
    implements _i3.CardScanResult {
  _FakeCardScanResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCardCollection_2 extends _i1.SmartFake
    implements _i4.CardCollection {
  _FakeCardCollection_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionStatistics_3 extends _i1.SmartFake
    implements _i5.CollectionStatistics {
  _FakeCollectionStatistics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScanQRCode].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanQRCode extends _i1.Mock implements _i6.ScanQRCode {
  MockScanQRCode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CardRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCardRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CardRepository);

  @override
  _i7.Future<_i3.CardScanResult> call(
    int? guardianId,
    String? qrCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            guardianId,
            qrCode,
          ],
        ),
        returnValue: _i7.Future<_i3.CardScanResult>.value(_FakeCardScanResult_1(
          this,
          Invocation.method(
            #call,
            [
              guardianId,
              qrCode,
            ],
          ),
        )),
      ) as _i7.Future<_i3.CardScanResult>);
}

/// A class which mocks [GetCardCollection].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCardCollection extends _i1.Mock implements _i8.GetCardCollection {
  MockGetCardCollection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CardRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCardRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CardRepository);

  @override
  _i7.Future<_i4.CardCollection> call(int? guardianId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [guardianId],
        ),
        returnValue: _i7.Future<_i4.CardCollection>.value(_FakeCardCollection_2(
          this,
          Invocation.method(
            #call,
            [guardianId],
          ),
        )),
      ) as _i7.Future<_i4.CardCollection>);
}

/// A class which mocks [GetCollectionStatistics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCollectionStatistics extends _i1.Mock
    implements _i9.GetCollectionStatistics {
  MockGetCollectionStatistics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CardRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCardRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CardRepository);

  @override
  _i7.Future<_i5.CollectionStatistics> call(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [guardianId],
        ),
        returnValue: _i7.Future<_i5.CollectionStatistics>.value(
            _FakeCollectionStatistics_3(
          this,
          Invocation.method(
            #call,
            [guardianId],
          ),
        )),
      ) as _i7.Future<_i5.CollectionStatistics>);
}

/// A class which mocks [SearchCards].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchCards extends _i1.Mock implements _i10.SearchCards {
  MockSearchCards() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CardRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCardRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CardRepository);

  @override
  _i7.Future<List<_i11.Card>> call({
    String? name,
    _i11.CardElement? element,
    _i11.CardRarity? rarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #name: name,
            #element: element,
            #rarity: rarity,
          },
        ),
        returnValue: _i7.Future<List<_i11.Card>>.value(<_i11.Card>[]),
      ) as _i7.Future<List<_i11.Card>>);
}

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i2.CardRepository {
  MockCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.CardScanResult> scanQRCode(
    int? guardianId,
    String? qrCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanQRCode,
          [
            guardianId,
            qrCode,
          ],
        ),
        returnValue: _i7.Future<_i3.CardScanResult>.value(_FakeCardScanResult_1(
          this,
          Invocation.method(
            #scanQRCode,
            [
              guardianId,
              qrCode,
            ],
          ),
        )),
      ) as _i7.Future<_i3.CardScanResult>);

  @override
  _i7.Future<_i4.CardCollection> getGuardianCollection(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuardianCollection,
          [guardianId],
        ),
        returnValue: _i7.Future<_i4.CardCollection>.value(_FakeCardCollection_2(
          this,
          Invocation.method(
            #getGuardianCollection,
            [guardianId],
          ),
        )),
      ) as _i7.Future<_i4.CardCollection>);

  @override
  _i7.Future<List<_i12.CollectedCard>> getGuardianCards(
    int? guardianId, {
    _i11.CardElement? element,
    _i11.CardRarity? rarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuardianCards,
          [guardianId],
          {
            #element: element,
            #rarity: rarity,
          },
        ),
        returnValue:
            _i7.Future<List<_i12.CollectedCard>>.value(<_i12.CollectedCard>[]),
      ) as _i7.Future<List<_i12.CollectedCard>>);

  @override
  _i7.Future<_i5.CollectionStatistics> getCollectionStatistics(
          int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionStatistics,
          [guardianId],
        ),
        returnValue: _i7.Future<_i5.CollectionStatistics>.value(
            _FakeCollectionStatistics_3(
          this,
          Invocation.method(
            #getCollectionStatistics,
            [guardianId],
          ),
        )),
      ) as _i7.Future<_i5.CollectionStatistics>);

  @override
  _i7.Future<List<_i12.CollectedCard>> getRecentlyCollected(
    int? guardianId,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyCollected,
          [
            guardianId,
            limit,
          ],
        ),
        returnValue:
            _i7.Future<List<_i12.CollectedCard>>.value(<_i12.CollectedCard>[]),
      ) as _i7.Future<List<_i12.CollectedCard>>);

  @override
  _i7.Future<_i12.CollectedCard?> getRarestCard(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRarestCard,
          [guardianId],
        ),
        returnValue: _i7.Future<_i12.CollectedCard?>.value(),
      ) as _i7.Future<_i12.CollectedCard?>);

  @override
  _i7.Future<List<_i11.Card>> searchCards({
    String? name,
    _i11.CardElement? element,
    _i11.CardRarity? rarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCards,
          [],
          {
            #name: name,
            #element: element,
            #rarity: rarity,
          },
        ),
        returnValue: _i7.Future<List<_i11.Card>>.value(<_i11.Card>[]),
      ) as _i7.Future<List<_i11.Card>>);

  @override
  _i7.Future<_i11.Card?> getCard(int? cardId) => (super.noSuchMethod(
        Invocation.method(
          #getCard,
          [cardId],
        ),
        returnValue: _i7.Future<_i11.Card?>.value(),
      ) as _i7.Future<_i11.Card?>);
}
