name: 'Cleanup Workspace'
description: 'Cleans root-owned files from workspace on self-hosted runners'
inputs:
  kill-containers:
    description: 'Whether to kill guardianes containers before cleanup'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 🧹 Cleanup Workspace
      shell: bash
      run: |
        # Optional: Kill only guardianes containers (not all containers)
        if [ "${{ inputs.kill-containers }}" = "true" ]; then
          echo "🛑 Stopping guardianes containers..."
          docker ps -q --filter "name=guardianes" | xargs -r docker kill || true
          docker ps -aq --filter "name=guardianes" | xargs -r docker rm -f || true
        fi
        
        # Use Docker to fix file permissions (with proper UID/GID)
        echo "🧹 Fixing file permissions in workspace..."
        docker run --rm --user root \
          -v "${{ github.workspace }}:/workspace" \
          alpine:latest \
          sh -c "chown -R $(id -u):$(id -g) /workspace 2>/dev/null || true"
        
        # Clean specific directories known to have root-owned files
        echo "🧹 Cleaning docker config directories..."
        docker run --rm --user root \
          -v "${{ github.workspace }}:/workspace" \
          alpine:latest \
          sh -c "rm -rf /workspace/docker/redis /workspace/docker/grafana 2>/dev/null || true; \
                 find /workspace -name 'target' -type d -exec rm -rf {} + 2>/dev/null || true"
        
        # Reset git repository state if it exists
        cd "${{ github.workspace }}" 2>/dev/null && git reset --hard HEAD 2>/dev/null || true
        
        # Ensure proper ownership
        chown -R $(id -u):$(id -g) "${{ github.workspace }}" 2>/dev/null || true
