// Mocks generated by Mockito 5.4.6 from annotations
// in guardianes_mobile/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:guardianes_mobile/features/auth/data/datasources/auth_local_datasource.dart'
    as _i6;
import 'package:guardianes_mobile/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i4;
import 'package:guardianes_mobile/features/auth/data/datasources/guardian_profile_remote_datasource.dart'
    as _i7;
import 'package:guardianes_mobile/features/auth/data/models/auth_response_model.dart'
    as _i2;
import 'package:guardianes_mobile/features/auth/data/models/guardian_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponseModel_0 extends _i1.SmartFake
    implements _i2.AuthResponseModel {
  _FakeAuthResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGuardianModel_1 extends _i1.SmartFake implements _i3.GuardianModel {
  _FakeGuardianModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthResponseModel> register({
    required String? username,
    required String? email,
    required String? password,
    required String? name,
    required DateTime? birthDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #username: username,
            #email: email,
            #password: password,
            #name: name,
            #birthDate: birthDate,
          },
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #register,
            [],
            {
              #username: username,
              #email: email,
              #password: password,
              #name: name,
              #birthDate: birthDate,
            },
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseModel>);

  @override
  _i5.Future<_i2.AuthResponseModel> login({
    required String? usernameOrEmail,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #usernameOrEmail: usernameOrEmail,
            #password: password,
          },
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #usernameOrEmail: usernameOrEmail,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseModel>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i6.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> removeToken() => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveGuardian(_i3.GuardianModel? guardian) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGuardian,
          [guardian],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.GuardianModel?> getGuardian() => (super.noSuchMethod(
        Invocation.method(
          #getGuardian,
          [],
        ),
        returnValue: _i5.Future<_i3.GuardianModel?>.value(),
      ) as _i5.Future<_i3.GuardianModel?>);

  @override
  _i5.Future<void> removeGuardian() => (super.noSuchMethod(
        Invocation.method(
          #removeGuardian,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GuardianProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuardianProfileRemoteDataSource extends _i1.Mock
    implements _i7.GuardianProfileRemoteDataSource {
  MockGuardianProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.GuardianModel> getGuardianProfile(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuardianProfile,
          [guardianId],
        ),
        returnValue: _i5.Future<_i3.GuardianModel>.value(_FakeGuardianModel_1(
          this,
          Invocation.method(
            #getGuardianProfile,
            [guardianId],
          ),
        )),
      ) as _i5.Future<_i3.GuardianModel>);

  @override
  _i5.Future<_i3.GuardianModel> updateGuardianProfile(
    int? guardianId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGuardianProfile,
          [
            guardianId,
            updates,
          ],
        ),
        returnValue: _i5.Future<_i3.GuardianModel>.value(_FakeGuardianModel_1(
          this,
          Invocation.method(
            #updateGuardianProfile,
            [
              guardianId,
              updates,
            ],
          ),
        )),
      ) as _i5.Future<_i3.GuardianModel>);
}
