apiVersion: v2
name: guardianes-de-gaia
description: A Helm chart for Guardianes de Gaia mobile game backend and infrastructure
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - mobile-game
  - spring-boot
  - educational
  - gamification
  - walking

home: https://github.com/guardianes-de-gaia/guardianes-de-gaia
sources:
  - https://github.com/guardianes-de-gaia/guardianes-de-gaia

maintainers:
  - name: Guardianes de Gaia Team
    email: team@guardianes-de-gaia.com

# Dependencies removed for production-grade self-contained deployment
# External services should be deployed separately in production
# dependencies:

annotations:
  category: Application
  licenses: MIT