// Mocks generated by Mockito 5.4.6 from annotations
// in guardianes_mobile/test/features/walking/domain/usecases/get_step_history_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:guardianes_mobile/features/walking/domain/entities/daily_step_aggregate.dart'
    as _i2;
import 'package:guardianes_mobile/features/walking/domain/entities/step_record.dart'
    as _i5;
import 'package:guardianes_mobile/features/walking/domain/repositories/step_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDailyStepAggregate_0 extends _i1.SmartFake
    implements _i2.DailyStepAggregate {
  _FakeDailyStepAggregate_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StepRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStepRepository extends _i1.Mock implements _i3.StepRepository {
  MockStepRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> submitSteps(_i5.StepRecord? stepRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitSteps,
          [stepRecord],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.DailyStepAggregate> getCurrentStepCount(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentStepCount,
          [guardianId],
        ),
        returnValue:
            _i4.Future<_i2.DailyStepAggregate>.value(_FakeDailyStepAggregate_0(
          this,
          Invocation.method(
            #getCurrentStepCount,
            [guardianId],
          ),
        )),
      ) as _i4.Future<_i2.DailyStepAggregate>);

  @override
  _i4.Future<List<_i2.DailyStepAggregate>> getStepHistory(
    int? guardianId,
    String? fromDate,
    String? toDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStepHistory,
          [
            guardianId,
            fromDate,
            toDate,
          ],
        ),
        returnValue: _i4.Future<List<_i2.DailyStepAggregate>>.value(
            <_i2.DailyStepAggregate>[]),
      ) as _i4.Future<List<_i2.DailyStepAggregate>>);
}
