name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mobile/**'
      - 'flutter/**'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'mobile/**'
      - 'flutter/**'
      - '.github/workflows/flutter-ci.yml'

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  test:
    name: Flutter Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      working-directory: ./mobile/guardianes_mobile
      run: flutter pub get

    - name: Verify Flutter installation
      run: flutter doctor -v

    - name: Analyze code
      working-directory: ./mobile/guardianes_mobile
      run: flutter analyze

    - name: Check formatting
      working-directory: ./mobile/guardianes_mobile
      run: dart format --set-exit-if-changed .

    - name: Run unit tests
      working-directory: ./mobile/guardianes_mobile
      run: flutter test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./mobile/guardianes_mobile/coverage/lcov.info
        flags: flutter
        name: flutter-coverage

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Get dependencies
      working-directory: ./mobile/guardianes_mobile
      run: flutter pub get

    - name: Build APK
      working-directory: ./mobile/guardianes_mobile
      run: flutter build apk --release

    - name: Build App Bundle
      working-directory: ./mobile/guardianes_mobile
      run: flutter build appbundle --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: mobile/guardianes_mobile/build/app/outputs/flutter-apk/app-release.apk

    - name: Upload App Bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: mobile/guardianes_mobile/build/app/outputs/bundle/release/app-release.aab

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      working-directory: ./mobile/guardianes_mobile
      run: flutter pub get

    - name: Build iOS (no codesign)
      working-directory: ./mobile/guardianes_mobile
      run: flutter build ios --release --no-codesign

    - name: Upload iOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: mobile/guardianes_mobile/build/ios/iphoneos/Runner.app

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      working-directory: ./mobile/guardianes_mobile
      run: flutter pub get

    - name: Run integration tests
      working-directory: ./mobile/guardianes_mobile
      run: flutter test integration_test/
      continue-on-error: true

  web-build:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      working-directory: ./mobile/guardianes_mobile
      run: flutter pub get

    - name: Build web
      working-directory: ./mobile/guardianes_mobile
      run: flutter build web --release

    - name: Upload web build artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: mobile/guardianes_mobile/build/web/

  performance-test:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      working-directory: ./mobile/guardianes_mobile
      run: flutter pub get

    - name: Run performance tests
      working-directory: ./mobile/guardianes_mobile
      run: |
        flutter test test_driver/performance_test.dart || echo "Performance tests not yet implemented"