// Mocks generated by Mockito 5.4.6 from annotations
// in guardianes_mobile/test/features/cards/domain/usecases/get_card_collection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:guardianes_mobile/features/cards/domain/entities/card.dart'
    as _i8;
import 'package:guardianes_mobile/features/cards/domain/entities/card_collection.dart'
    as _i3;
import 'package:guardianes_mobile/features/cards/domain/entities/card_scan_result.dart'
    as _i2;
import 'package:guardianes_mobile/features/cards/domain/entities/collected_card.dart'
    as _i7;
import 'package:guardianes_mobile/features/cards/domain/entities/collection_statistics.dart'
    as _i4;
import 'package:guardianes_mobile/features/cards/domain/repositories/card_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCardScanResult_0 extends _i1.SmartFake
    implements _i2.CardScanResult {
  _FakeCardScanResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCardCollection_1 extends _i1.SmartFake
    implements _i3.CardCollection {
  _FakeCardCollection_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionStatistics_2 extends _i1.SmartFake
    implements _i4.CollectionStatistics {
  _FakeCollectionStatistics_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i5.CardRepository {
  MockCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CardScanResult> scanQRCode(
    int? guardianId,
    String? qrCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanQRCode,
          [
            guardianId,
            qrCode,
          ],
        ),
        returnValue: _i6.Future<_i2.CardScanResult>.value(_FakeCardScanResult_0(
          this,
          Invocation.method(
            #scanQRCode,
            [
              guardianId,
              qrCode,
            ],
          ),
        )),
      ) as _i6.Future<_i2.CardScanResult>);

  @override
  _i6.Future<_i3.CardCollection> getGuardianCollection(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuardianCollection,
          [guardianId],
        ),
        returnValue: _i6.Future<_i3.CardCollection>.value(_FakeCardCollection_1(
          this,
          Invocation.method(
            #getGuardianCollection,
            [guardianId],
          ),
        )),
      ) as _i6.Future<_i3.CardCollection>);

  @override
  _i6.Future<List<_i7.CollectedCard>> getGuardianCards(
    int? guardianId, {
    _i8.CardElement? element,
    _i8.CardRarity? rarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuardianCards,
          [guardianId],
          {
            #element: element,
            #rarity: rarity,
          },
        ),
        returnValue:
            _i6.Future<List<_i7.CollectedCard>>.value(<_i7.CollectedCard>[]),
      ) as _i6.Future<List<_i7.CollectedCard>>);

  @override
  _i6.Future<_i4.CollectionStatistics> getCollectionStatistics(
          int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionStatistics,
          [guardianId],
        ),
        returnValue: _i6.Future<_i4.CollectionStatistics>.value(
            _FakeCollectionStatistics_2(
          this,
          Invocation.method(
            #getCollectionStatistics,
            [guardianId],
          ),
        )),
      ) as _i6.Future<_i4.CollectionStatistics>);

  @override
  _i6.Future<List<_i7.CollectedCard>> getRecentlyCollected(
    int? guardianId,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyCollected,
          [
            guardianId,
            limit,
          ],
        ),
        returnValue:
            _i6.Future<List<_i7.CollectedCard>>.value(<_i7.CollectedCard>[]),
      ) as _i6.Future<List<_i7.CollectedCard>>);

  @override
  _i6.Future<_i7.CollectedCard?> getRarestCard(int? guardianId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRarestCard,
          [guardianId],
        ),
        returnValue: _i6.Future<_i7.CollectedCard?>.value(),
      ) as _i6.Future<_i7.CollectedCard?>);

  @override
  _i6.Future<List<_i8.Card>> searchCards({
    String? name,
    _i8.CardElement? element,
    _i8.CardRarity? rarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCards,
          [],
          {
            #name: name,
            #element: element,
            #rarity: rarity,
          },
        ),
        returnValue: _i6.Future<List<_i8.Card>>.value(<_i8.Card>[]),
      ) as _i6.Future<List<_i8.Card>>);

  @override
  _i6.Future<_i8.Card?> getCard(int? cardId) => (super.noSuchMethod(
        Invocation.method(
          #getCard,
          [cardId],
        ),
        returnValue: _i6.Future<_i8.Card?>.value(),
      ) as _i6.Future<_i8.Card?>);
}
